# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Azure Pipelines
  demands: maven

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’
#Create or edit the build pipeline for this YAML file, define the variable on the Variables tab.
#See https://go.microsoft.com/fwlink/?linkid=865972


steps:
  - task: JavaToolInstaller@0
    displayName: 'Use Java 11'
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled

  - task: Maven@3
    displayName: 'Maven pom.xml'
    inputs:
      mavenPomFile: '$(Parameters.mavenPOMFile)'
      options: '-P"Web Parallel execution"'
      jdkVersionOption: 1.11

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
      CleanTargetFolder: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
